In [1]:
import pandas as pd
from pathlib import Path

In [2]:
FILE_PATH = "data/capstone"
kilt_dpr_100w_fixed = Path(FILE_PATH) / "kilt_dpr_100w_fixed.parquet"

In [11]:
import polars as pl
import gc

# --- CONFIGURATION ---
FILE_PATH = "data/capstone/kilt_dpr_100w_fixed.parquet"
CHUNK_SIZE = 5               # Read 5 rows at a time
MAX_CHUNKS_TO_PRINT = 3      # Stop after printing 3 chunks

def main():
    print(f"🔍 Scanning file: {FILE_PATH}...")
    
    try:
        # 1. Create a LazyFrame (does NOT load data into RAM)
        lf = pl.scan_parquet(FILE_PATH)
        
        # Get total rows safely
        total_rows = lf.select(pl.len()).collect().item()
        print(f"📊 Total rows in file: {total_rows:,}\n")
        print("-" * 50)
        
    except FileNotFoundError:
        print(f"❌ Could not find {FILE_PATH}. Check your path!")
        return

    offset = 0
    chunks_printed = 0
    
    # 2. Loop through the file in chunks
    while offset < total_rows:
        # Slice the exact rows we want, then pull ONLY those into RAM
        df_chunk = lf.slice(offset, CHUNK_SIZE).collect()
        
        if df_chunk.is_empty():
            break
            
        print(f"📦 --- CHUNK {chunks_printed + 1} (Offset: {offset}) ---")
        
        # Print the data (Polars automatically formats this nicely in the console)
        print(df_chunk.show())
        print(df_chunk["text"][0])
        print("\n")
        
        # Move our pointer forward
        offset += CHUNK_SIZE
        chunks_printed += 1
        
        # 3. Explicit Memory Cleanup
        del df_chunk
        gc.collect()
        
        # Stop early so we don't print millions of rows
        if chunks_printed >= MAX_CHUNKS_TO_PRINT:
            print("🛑 Reached max chunks to print. Stopping safely.")
            break

if __name__ == "__main__":
    main()

🔍 Scanning file: data/capstone/kilt_dpr_100w_fixed.parquet...
📊 Total rows in file: 29,172,079

--------------------------------------------------
📦 --- CHUNK 1 (Offset: 0) ---

wikipedia_id,text,title,chunk_id
str,str,str,i64
"""290""","""A A (named , plural ""As"", ""A's…","""A""",0
"""290""","""also found in italic type. In …","""A""",1
"""290""","""that served as the base for so…","""A""",2
"""290""","""the 8th century BC, the letter…","""A""",3
"""290""","""English. Section::::History.:T…","""A""",4

None
A A (named , plural "As", "A's", "a"s, "a's" or "aes") is the first letter and the first vowel of the modern English alphabet and the ISO basic Latin alphabet. It is similar to the Ancient Greek letter alpha, from which it derives. The uppercase version consists of the two slanting sides of a triangle, crossed in the middle by a horizontal bar. The lowercase version can be written in two forms: the double-storey a and single-storey ɑ. The latter is commonly used in handwriting and fonts based on it, especially fonts intended to be read by children, and is


📦 --- CHUNK 2 (Offset: 5) ---

wikipedia_id,text,title,chunk_id
str,str,str,i64
"""290""","""were intermediate between the …","""A""",5
"""290""","""This form was derived through …","""A""",6
"""290""","""(""a""). Both derive from the ma…","""A""",7
"""290""","""are some other cases aside fro…","""A""",8
"""290""","""vowel letter) – this results f…","""A""",9

None
were intermediate between the monumental and cursive styles. The known variants include the early semi-uncial, the uncial, and the later semi-uncial. At the end of the Roman Empire (5th century AD), several variants of the cursive minuscule developed through Western Europe. Among these were the semicursive minuscule of Italy, the Merovingian script in France, the Visigothic script in Spain, and the Insular or Anglo-Irish semi-uncial or Anglo-Saxon majuscule of Great Britain. By the 9th century, the Caroline script, which was very similar to the present-day form, was the principal form used in book-making, before the advent of the printing press.


📦 --- CHUNK 3 (Offset: 10) ---

wikipedia_id,text,title,chunk_id
str,str,str,i64
"""290""","""sounds, particularly , , , , a…","""A""",10
"""290""","""unrounded vowel and is used fo…","""A""",11
"""290""","""denote something or someone of…","""A""",12
"""290""","""size, as in a narrow size shoe…","""A""",13
"""290""","""Ą́ ą́ Ą̃ ą̃ A̲ a̲ ᶏ BULLET::::…","""A""",14

None
sounds, particularly , , , , and . Section::::Use in writing systems.:Other languages. In most languages that use the Latin alphabet, denotes an open unrounded vowel, such as , , or . An exception is Saanich, in which (and the glyph Á) stands for a close-mid front unrounded vowel . Section::::Use in writing systems.:Other systems. In phonetic and phonemic notation: BULLET::::- in the International Phonetic Alphabet, is used for the open front unrounded vowel, is used for the open central unrounded vowel, and is used for the open back unrounded vowel. BULLET::::- in X-SAMPA, is used for the open front


🛑 Reached max chunks to print. Stopping safely.